"use client";

import dynamic from "next/dynamic";
import type { Route } from "next";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState, useTransition } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { ActivityIcon, ArrowIcon, PlusIcon, SearchIcon } from "@/components/icons";
import { Modal, Toast } from "@/components/overlay";
import { Badge } from "@/components/ui";
import type { ActivityPayload, ActivityType } from "@/lib/activity-api";
import { hydrateMockActivities, persistMockActivities } from "@/lib/mock-activity-store";
import { hydrateMockCompanies } from "@/lib/mock-company-store";
import { hydrateMockContacts } from "@/lib/mock-contact-store";
import { hydrateMockDeals } from "@/lib/mock-deal-store";
import { hydrateMockProjects } from "@/lib/mock-project-store";
import { buildRelationOptions } from "@/lib/relation-options";
import type { Activity, Company, Contact, Deal, Project, RelationType, WorkspaceUser } from "@/lib/types";

const ActivityForm = dynamic(() => import("./activity-form").then((module) => module.ActivityForm), { loading: () => <div className="form-loading" aria-hidden="true"><div /><div /><div /></div> });
const PAGE_SIZE = 12;
function makeId() { return `activity-${Date.now().toString(36)}`; }
function relationHref(type: RelationType, id: string): Route { if (type === "COMPANY") return `/companies/${id}` as Route; if (type === "CONTACT") return `/contacts/${id}` as Route; if (type === "DEAL") return `/deals/${id}` as Route; return `/projects/${id}` as Route; }
function formatActivityTime(value: string) { return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function activityTone(type: ActivityType) { if (type === "MEETING") return "blue" as const; if (type === "UPDATE") return "yellow" as const; return "neutral" as const; }

export function ActivitiesWorkspace({ seedActivities, seedCompanies, seedContacts, seedDeals, seedProjects, owners }: { seedActivities: Activity[]; seedCompanies: Company[]; seedContacts: Contact[]; seedDeals: Deal[]; seedProjects: Project[]; owners: WorkspaceUser[] }) {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams();
  const [records, setRecords] = useState(seedActivities); const [search, setSearch] = useState(searchParams.get("search") ?? ""); const [logging, setLogging] = useState(false); const [toast, setToast] = useState<string | null>(null); const [isNavigating, startTransition] = useTransition();
  const [relations, setRelations] = useState(() => buildRelationOptions({ companies: seedCompanies, contacts: seedContacts, deals: seedDeals, projects: seedProjects }));
  useEffect(() => {
    setRecords(hydrateMockActivities(seedActivities));
    setRelations(buildRelationOptions({ companies: hydrateMockCompanies(seedCompanies), contacts: hydrateMockContacts(seedContacts), deals: hydrateMockDeals(seedDeals), projects: hydrateMockProjects(seedProjects) }));
  }, [seedActivities, seedCompanies, seedContacts, seedDeals, seedProjects]);
  const relationByKey = useMemo(() => new Map(relations.map((item) => [`${item.type}:${item.id}`, item])), [relations]);
  const actorById = useMemo(() => new Map(owners.map((item) => [item.id, item.name])), [owners]);
  const updateQuery = useCallback((changes: Record<string, string | number | null>) => { const params = new URLSearchParams(searchParams.toString()); Object.entries(changes).forEach(([key, value]) => { if (value === null || value === "" || value === 1) params.delete(key); else params.set(key, String(value)); }); const query = params.toString(); startTransition(() => router.replace((query ? `${pathname}?${query}` : pathname) as Route, { scroll: false })); }, [pathname, router, searchParams]);
  const urlSearch = searchParams.get("search") ?? "";
  useEffect(() => { if (search === urlSearch) return; const timer = window.setTimeout(() => updateQuery({ search: search.trim(), page: 1 }), 250); return () => window.clearTimeout(timer); }, [search, updateQuery, urlSearch]); useEffect(() => setSearch(urlSearch), [urlSearch]);
  useEffect(() => { if (searchParams.get("new") === "1") setLogging(true); }, [searchParams]);
  const type = searchParams.get("type") as ActivityType | ""; const actorId = searchParams.get("actorId") ?? ""; const companyId = searchParams.get("companyId") ?? ""; const relationType = searchParams.get("relationType") as RelationType | ""; const pageRequested = Math.max(1, Number(searchParams.get("page") ?? 1) || 1);
  const filtered = useMemo(() => records.filter((activity) => { const relation = relationByKey.get(`${activity.relationType}:${activity.relationId}`)?.label ?? activity.relation; const q = urlSearch.toLowerCase(); if (q && !`${activity.title} ${activity.detail} ${activity.actor} ${relation}`.toLowerCase().includes(q)) return false; if (type && activity.type !== type) return false; if (actorId && activity.actorId !== actorId) return false; if (companyId && relationByKey.get(`${activity.relationType}:${activity.relationId}`)?.companyId !== companyId) return false; if (relationType && activity.relationType !== relationType) return false; return true; }).sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt)), [records, relationByKey, urlSearch, type, actorId, companyId, relationType]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const page = Math.min(pageRequested, totalPages); const pageRecords = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  function close() { setLogging(false); updateQuery({ new: null }); }
  function save(values: ActivityPayload) { const relation = relationByKey.get(`${values.relationType}:${values.relationId}`); const actor = owners.find((item) => item.id === values.actorId); if (!relation || !actor) return; const now = values.occurredAt ?? new Date().toISOString(); const activity: Activity = { id: makeId(), createdAt: now, updatedAt: now, type: values.type, title: values.title, detail: values.detail, actorId: values.actorId, actor: actor.name, time: formatActivityTime(now).replace(",", " ·"), relationType: values.relationType, relationId: values.relationId, relation: relation.label }; const next = [activity, ...records]; persistMockActivities(next); setRecords(next); setToast("Activity logged."); close(); }
  const todayCount = records.filter((item) => new Date(item.createdAt).toDateString() === new Date().toDateString()).length; const meetingCount = records.filter((item) => item.type === "MEETING").length; const noteCount = records.filter((item) => item.type === "NOTE").length;
  return <>
    <div className="page-header"><div><div className="eyebrow">TRACEABILITY / 01 ──</div><h1>Activities</h1><p>A chronological record of customer interactions, material notes and CRM changes.</p></div><button className="primary-button" type="button" onClick={() => setLogging(true)}><PlusIcon />Log activity</button></div>
    <div className="activity-metrics"><div><span>TOTAL TRACE</span><strong>{records.length}</strong><small>Logged interactions</small></div><div><span>TODAY</span><strong>{todayCount}</strong><small>New context</small></div><div><span>MEETINGS</span><strong>{meetingCount}</strong><small>Stakeholder touchpoints</small></div><div><span>NOTES</span><strong>{noteCount}</strong><small>Retained context</small></div></div>
    <div className={`records-toolbar ${isNavigating ? "is-navigating" : ""}`}><div className="toolbar-tools activity-toolbar-tools"><label className="inline-search activity-search"><SearchIcon /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search activity, context or actor..." /></label><label className="sort-control"><span>TYPE</span><select value={type} onChange={(event) => updateQuery({ type: event.target.value, page: 1 })}><option value="">All types</option><option value="MEETING">Meeting</option><option value="CALL">Call</option><option value="EMAIL">Email</option><option value="NOTE">Note</option><option value="UPDATE">Update</option></select></label><label className="sort-control"><span>RELATION</span><select value={relationType} onChange={(event) => updateQuery({ relationType: event.target.value, page: 1 })}><option value="">All relations</option><option value="COMPANY">Company</option><option value="CONTACT">Contact</option><option value="DEAL">Deal</option><option value="PROJECT">Project</option></select></label><label className="sort-control"><span>ACCOUNT</span><select value={companyId} onChange={(event) => updateQuery({ companyId: event.target.value, page: 1 })}><option value="">All accounts</option>{seedCompanies.filter((company) => !company.archivedAt).map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label><label className="sort-control"><span>ACTOR</span><select value={actorId} onChange={(event) => updateQuery({ actorId: event.target.value, page: 1 })}><option value="">Anyone</option>{owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.name}</option>)}</select></label></div></div>
    {pageRecords.length ? <div className="timeline-panel activity-workspace-timeline">{pageRecords.map((activity, index) => { const relation = relationByKey.get(`${activity.relationType}:${activity.relationId}`); return <div className="timeline-row" key={activity.id}><div className="timeline-time"><span>{formatActivityTime(activity.createdAt).split(",")[0]}</span><small>{formatActivityTime(activity.createdAt).split(",")[1]?.trim()}</small></div><div className="timeline-axis"><span className="timeline-dot" />{index < pageRecords.length - 1 && <span className="timeline-line" />}</div><div className="timeline-content"><div className="timeline-title"><ActivityIcon /><strong>{activity.title}</strong><Badge tone={activityTone(activity.type)}>{activity.type}</Badge></div><p>{activity.detail}</p><div className="timeline-meta"><span>{actorById.get(activity.actorId) ?? activity.actor}</span><span>→</span><Link href={relationHref(activity.relationType, activity.relationId)}>{relation?.label ?? activity.relation}<ArrowIcon /></Link><span>{activity.relationType}</span></div></div></div>; })}</div> : <div className="data-empty"><ActivityIcon /><strong>No activity matches these filters.</strong><p>Log a customer touchpoint or reset the current filters.</p><button className="secondary-button" type="button" onClick={() => { setSearch(""); updateQuery({ search: null, type: null, actorId: null, companyId: null, relationType: null, page: 1 }); }}>Reset filters</button></div>}
    <div className="pagination-bar"><span>Showing {(page - 1) * PAGE_SIZE + (filtered.length ? 1 : 0)}–{Math.min(page * PAGE_SIZE, filtered.length)} of {filtered.length}</span><div className="pagination-controls"><button type="button" disabled={page <= 1} onClick={() => updateQuery({ page: page - 1 })}>← Previous</button><span>{page} / {totalPages}</span><button type="button" disabled={page >= totalPages} onClick={() => updateQuery({ page: page + 1 })}>Next →</button></div></div>
    <Modal open={logging} onClose={close} eyebrow="TRACEABILITY / Activity" title="Log activity" size="lg" footer={<><button className="secondary-button" type="button" onClick={close}>Cancel</button><button className="primary-button" type="submit" form="activity-form">Log activity</button></>}><ActivityForm relations={relations} owners={owners} defaultRelation={searchParams.get("relationType") && searchParams.get("relationId") ? { type: searchParams.get("relationType") as RelationType, id: searchParams.get("relationId")! } : undefined} onSubmit={save} /></Modal>
    {toast && <Toast message={toast} onClose={() => setToast(null)} />}
  </>;
}
